"use client";
import Image from "next/image";
import Link from "next/link";
import { useMemo, useState } from "react";
import { ArrowLeft, CalendarClock, Check, ChevronDown, Clock3, Globe2, ImageIcon, MonitorPlay, Music2, Play, Send } from "lucide-react";

const networks=[{id:"youtube",name:"YouTube",account:"Studio Nova",icon:MonitorPlay,color:"bg-red-50 text-red-600"},{id:"tiktok",name:"TikTok",account:"@studionova",icon:Music2,color:"bg-slate-900 text-white"},{id:"instagram",name:"Instagram",account:"@studionova",icon:ImageIcon,color:"bg-pink-50 text-pink-600"},{id:"facebook",name:"Facebook",account:"Studio Nova",icon:Globe2,color:"bg-blue-50 text-blue-600"}];

export function Composer(){
 const [selected,setSelected]=useState(["youtube","instagram"]);const [mode,setMode]=useState<"now"|"later">("later");const [title,setTitle]=useState("Le déclic que personne ne voit");const [description,setDescription]=useState("Le meilleur moment arrive souvent quand on arrête de le forcer. Voici ce que j’ai appris.\n\n#creation #entrepreneur #shorts");const [advanced,setAdvanced]=useState(false);const active=useMemo(()=>networks.filter(n=>selected.includes(n.id)),[selected]);
 const toggle=(id:string)=>setSelected(values=>values.includes(id)?values.filter(value=>value!==id):[...values,id]);
 return <div className="mx-auto max-w-[1400px]"><header className="flex flex-wrap items-end justify-between gap-4"><div><Link href="/dashboard/videos/demo" className="mb-4 flex items-center gap-2 text-sm font-bold text-slate-500"><ArrowLeft size={16}/> Retour au studio</Link><p className="text-sm font-black uppercase tracking-[.15em] text-lime-700">Nouvelle publication</p><h1 className="mt-1 text-3xl font-black tracking-[-.04em] md:text-4xl">Préparez chaque destination.</h1><p className="mt-2 text-sm text-slate-500">Un contenu commun, une publication adaptée par réseau.</p></div><div className="flex items-center gap-2"><button className="rounded-full border bg-white px-5 py-3 text-sm font-black">Enregistrer le brouillon</button><button disabled={!selected.length} className="flex items-center gap-2 rounded-full bg-[#172033] px-5 py-3 text-sm font-black text-white disabled:opacity-40"><Send size={16}/>{mode==="now"?"Publier maintenant":"Programmer"}</button></div></header>
 <div className="mt-7 grid gap-6 xl:grid-cols-[1fr_390px]"><div className="space-y-5"><section className="rounded-3xl border bg-white p-5 sm:p-6"><h2 className="text-lg font-black">1. Choisissez les réseaux</h2><p className="mt-1 text-sm text-slate-500">Une publication distincte sera créée pour chaque compte.</p><div className="mt-5 grid gap-3 sm:grid-cols-2">{networks.map(({id,name,account,icon:Icon,color})=>{const checked=selected.includes(id);return <button key={id} onClick={()=>toggle(id)} className={`flex items-center gap-3 rounded-2xl border p-3 text-left ${checked?"border-lime-500 bg-lime-50":"hover:bg-slate-50"}`}><span className={`grid h-10 w-10 place-items-center rounded-xl ${color}`}><Icon size={20} fill={id==="tiktok"?"currentColor":"none"}/></span><span className="flex-1"><span className="block font-black">{name}</span><span className="block text-xs text-slate-500">{account}</span></span><span className={`grid h-5 w-5 place-items-center rounded-full border ${checked?"border-lime-600 bg-lime-600 text-white":""}`}>{checked&&<Check size={12}/>}</span></button>})}</div></section>
 <section className="rounded-3xl border bg-white p-5 sm:p-6"><h2 className="text-lg font-black">2. Rédigez le message</h2><div className="mt-5 space-y-4"><label className="block text-sm font-bold">Titre<input value={title} onChange={e=>setTitle(e.target.value)} maxLength={255} className="mt-2 h-12 w-full rounded-2xl border bg-slate-50 px-4 font-normal outline-none focus:ring-2 focus:ring-lime-400"/></label><label className="block text-sm font-bold">Description<textarea value={description} onChange={e=>setDescription(e.target.value)} rows={6} className="mt-2 w-full resize-y rounded-2xl border bg-slate-50 px-4 py-3 font-normal leading-6 outline-none focus:ring-2 focus:ring-lime-400"/><span className="mt-1 block text-right text-xs font-normal text-slate-400">{description.length} caractères</span></label><button onClick={()=>setAdvanced(value=>!value)} className="flex items-center gap-2 text-sm font-black">Personnaliser par réseau <ChevronDown className={advanced?"rotate-180":""} size={16}/></button>{advanced&&<div className="rounded-2xl bg-orange-50 p-4 text-sm text-slate-600">Les variantes spécifiques à YouTube, TikTok, Instagram et Facebook seront affichées ici après sélection d’un réseau.</div>}</div></section>
 <section className="rounded-3xl border bg-white p-5 sm:p-6"><h2 className="text-lg font-black">3. Choisissez le moment</h2><div className="mt-5 grid gap-3 sm:grid-cols-2"><button onClick={()=>setMode("now")} className={`flex items-center gap-3 rounded-2xl border p-4 text-left ${mode==="now"?"border-lime-500 bg-lime-50":""}`}><Send size={19}/><span><span className="block font-black">Maintenant</span><span className="text-xs text-slate-500">Après votre confirmation</span></span></button><button onClick={()=>setMode("later")} className={`flex items-center gap-3 rounded-2xl border p-4 text-left ${mode==="later"?"border-lime-500 bg-lime-50":""}`}><CalendarClock size={19}/><span><span className="block font-black">Programmer</span><span className="text-xs text-slate-500">Choisir une date future</span></span></button></div>{mode==="later"&&<div className="mt-4 grid gap-3 sm:grid-cols-2"><label className="text-sm font-bold">Date<input type="date" defaultValue="2026-08-15" className="mt-2 h-11 w-full rounded-xl border px-3 font-normal"/></label><label className="text-sm font-bold">Heure<input type="time" defaultValue="18:30" className="mt-2 h-11 w-full rounded-xl border px-3 font-normal"/></label><p className="sm:col-span-2 flex items-center gap-2 text-xs text-slate-500"><Clock3 size={13}/> Fuseau horaire : Africa/Ouagadougou (UTC+0)</p></div>}</section></div>
 <aside className="xl:sticky xl:top-24 xl:self-start"><section className="overflow-hidden rounded-3xl border bg-white"><div className="flex items-center justify-between border-b p-4"><div><p className="font-black">Aperçu</p><p className="text-xs text-slate-500">{active.length} destination{active.length>1?"s":""}</p></div><div className="flex -space-x-2">{active.map(({id,icon:Icon,color})=><span key={id} className={`grid h-8 w-8 place-items-center rounded-full border-2 border-white ${color}`}><Icon size={14}/></span>)}</div></div><div className="p-4"><div className="mx-auto max-w-[270px] overflow-hidden rounded-3xl border bg-white shadow-xl"><div className="flex items-center gap-2 p-3"><span className="grid h-8 w-8 place-items-center rounded-full bg-[#172033] text-xs font-black text-white">S</span><div><p className="text-xs font-black">Studio Nova</p><p className="text-[10px] text-slate-400">Publication programmée</p></div></div><p className="line-clamp-3 px-3 pb-3 text-xs leading-5">{description}</p><div className="relative aspect-[9/12]"><Image src="/images/shortpilot-creator-story.png" alt="Aperçu de la publication" fill className="object-cover"/><span className="absolute inset-0 grid place-items-center"><span className="grid h-11 w-11 place-items-center rounded-full bg-white/90"><Play size={15} fill="currentColor"/></span></span><div className="absolute inset-x-4 bottom-6 rounded-lg bg-black/55 p-2 text-center text-xs font-black text-white">Le meilleur moment arrive quand on arrête de le forcer.</div></div><div className="flex justify-around border-t py-3 text-[10px] font-bold text-slate-500"><span>J’aime</span><span>Commenter</span><span>Partager</span></div></div></div><div className="border-t bg-slate-50 p-4"><p className="text-xs font-bold text-slate-600">Avant validation</p><ul className="mt-2 space-y-1.5 text-xs text-slate-500"><li className="flex gap-2"><Check size={13} className="text-lime-600"/> Contenu prêt</li><li className="flex gap-2"><Check size={13} className="text-lime-600"/> Comptes connectés</li><li className="flex gap-2"><Check size={13} className="text-lime-600"/> Aucun crédit supplémentaire par réseau</li></ul></div></section></aside></div><p className="mt-5 text-xs text-slate-400">Interface de démonstration alignée avec la création batch du backend.</p></div>;
}
