import type { Metadata } from "next";
import Link from "next/link";
import { notFound } from "next/navigation";

const documents = {
  "mentions-legales": { title:"Mentions légales", intro:"Informations relatives à l’éditeur et à l’hébergement de ShortPilot.", sections:[["Éditeur","Les coordonnées définitives de la société éditrice, sa forme juridique et son numéro d’immatriculation seront complétés avant la mise en production."],["Hébergement","Les informations de l’hébergeur seront publiées lorsque l’infrastructure de production sera arrêtée."],["Contact","Pour toute question légale, une adresse dédiée sera ajoutée avant le lancement public."]] },
  confidentialite: { title:"Politique de confidentialité", intro:"Comment ShortPilot protège et utilise vos données.", sections:[["Données traitées","Nous traitons les informations de compte, médias confiés, connexions sociales et données nécessaires au fonctionnement du service."],["Finalités","Ces données servent à authentifier les utilisateurs, produire les contenus demandés, publier avec leur autorisation et sécuriser la plateforme."],["Vos droits","Les mécanismes d’accès, de rectification, d’export et de suppression seront accessibles depuis le compte. La version juridique finale précisera les contacts et délais applicables."]] },
  conditions: { title:"Conditions d’utilisation", intro:"Les règles essentielles d’utilisation de ShortPilot.", sections:[["Utilisation autorisée","Vous devez disposer des droits nécessaires sur les médias importés et respecter les règles des plateformes de destination."],["Service","Les fonctionnalités, quotas et conditions de facturation dépendent du plan sélectionné."],["Publication","Vous restez responsable des contenus validés et de leur conformité avant publication. Les conditions contractuelles définitives seront soumises avant le lancement commercial."]] },
  cookies: { title:"Gestion des cookies", intro:"Les technologies utilisées sur le site et dans l’application.", sections:[["Cookies essentiels","Ils permettent notamment la sécurité, l’authentification et la conservation des préférences nécessaires."],["Mesure d’audience","Les outils facultatifs de mesure ne seront activés qu’après configuration du consentement applicable."],["Préférences","Un centre de gestion permettra d’accepter, refuser ou modifier les choix non essentiels."]] },
} as const;
type Slug=keyof typeof documents;
export function generateStaticParams(){return Object.keys(documents).map(slug=>({slug}));}
export async function generateMetadata({params}:{params:Promise<{slug:string}>}):Promise<Metadata>{const {slug}=await params;return {title:documents[slug as Slug]?.title??"Informations légales"};}
export default async function LegalPage({params}:{params:Promise<{slug:string}>}){const {slug}=await params;const document=documents[slug as Slug];if(!document)notFound();return <main className="min-h-screen bg-[#fbfaf6] text-[#172033]"><nav className="mx-auto flex h-20 max-w-4xl items-center justify-between px-5"><Link href="/" className="text-xl font-black">Short<span className="text-lime-600">Pilot</span></Link><Link href="/" className="text-sm font-bold">Retour à l’accueil</Link></nav><article className="mx-auto max-w-4xl px-5 pb-24 pt-16"><p className="text-sm font-bold uppercase tracking-[.18em] text-orange-500">Informations légales</p><h1 className="mt-4 text-5xl font-black tracking-[-.05em] sm:text-6xl">{document.title}</h1><p className="mt-6 text-xl text-slate-600">{document.intro}</p><p className="mt-4 rounded-2xl bg-orange-50 p-4 text-sm text-orange-900">Document préparatoire à faire valider et compléter juridiquement avant le lancement commercial.</p><div className="mt-12 space-y-10">{document.sections.map(([title,text])=><section key={title}><h2 className="text-2xl font-black">{title}</h2><p className="mt-3 leading-7 text-slate-600">{text}</p></section>)}</div></article></main>;}
