import Link from "next/link";
import Image from "next/image";
import { ArrowRight, BriefcaseBusiness, Check, ChevronRight, Clock3, Coins, GraduationCap, Heart, Languages, Layers3, Play, Send, Sparkles, UsersRound, WandSparkles } from "lucide-react";

const plans = [
  { name:"Gratuit", price:"0", suffix:"pour commencer", description:"Laissez ShortPilot vous montrer ce qu’une vidéo peut encore devenir.", features:["3 créations offertes","1 connexion sociale","10 publications","1 Go de stockage"], cta:"Essayer gratuitement" },
  { name:"Creator", price:"19", suffix:"USD / mois", description:"Pour retrouver un rythme de publication sans sacrifier vos soirées.", features:["30 créations par mois","2 connexions sociales","100 publications","10 Go de stockage"], cta:"Choisir Creator", featured:true },
  { name:"Pro", price:"49", suffix:"USD / mois", description:"Pour les équipes qui transforment chaque tournage en véritable campagne.", features:["100 créations par mois","8 connexions sociales","500 publications","3 espaces de travail"], cta:"Passer à Pro" },
];

const faqs = [
  ["Est-ce que ShortPilot publie à ma place ?","Oui. Vous choisissez les comptes, la légende, la visibilité et le moment. ShortPilot prépare puis envoie chaque publication séparément."],
  ["Mes vidéos restent-elles privées ?","Vos médias sont isolés par espace de travail. Les accès sociaux sont chiffrés et les liens temporaires expirent."],
  ["Que se passe-t-il si un rendu échoue ?","Le crédit réservé est libéré lorsqu’aucun rendu utilisable n’a été produit. Une nouvelle tentative de publication ne consomme pas de crédit."],
  ["Puis-je commencer sans carte bancaire ?","Oui. Le plan Gratuit offre trois créations pour découvrir le parcours avant de choisir un abonnement."],
];

function Logo({ inverted = false }: { inverted?: boolean }) { return <Link href="/" className={`text-xl font-black tracking-[-.04em] ${inverted ? "text-white" : "text-[#172033]"}`}>Short<span className="text-lime-600">Pilot</span><span className="ml-1 inline-block h-2 w-2 rounded-full bg-orange-500"/></Link>; }

function ProductStory() {
  return <div className="relative mx-auto h-[520px] w-full max-w-[520px] lg:mx-0">
    <div className="absolute left-2 top-12 w-[66%] rotate-[-5deg] rounded-[30px] border border-white/70 bg-white p-4 shadow-2xl shadow-slate-900/15 sm:left-8">
      <div className="relative aspect-video overflow-hidden rounded-2xl bg-[#1d2639] text-white"><Image src="/images/shortpilot-creator-story.png" alt="Créatrice préparant ses vidéos avec ShortPilot" fill className="object-cover" priority/><div className="absolute inset-0 bg-gradient-to-t from-slate-950/70 via-transparent to-transparent"/><span className="absolute left-3 top-3 rounded-full bg-black/45 px-3 py-1 text-xs backdrop-blur">Épisode complet · 47:12</span><div className="absolute inset-0 grid place-items-center"><span className="grid h-14 w-14 place-items-center rounded-full bg-white text-slate-900 shadow-xl"><Play size={20} fill="currentColor"/></span></div></div>
      <div className="flex items-center justify-between pt-4"><div><p className="text-xs text-slate-400">VIDÉO SOURCE</p><p className="font-semibold">Mon dernier tournage.mp4</p></div><span className="rounded-full bg-slate-100 px-3 py-1 text-xs">1,8 Go</span></div>
    </div>
    <div className="absolute bottom-8 right-1 w-[46%] rotate-[5deg] rounded-[28px] border-4 border-slate-900 bg-slate-950 p-2 shadow-2xl sm:right-6">
      <div className="aspect-[9/16] overflow-hidden rounded-[20px] bg-orange-100 p-3"><div className="relative flex h-full flex-col justify-end overflow-hidden rounded-2xl bg-gradient-to-b from-[#dce9c9] via-[#f7cda8] to-[#2d384b] p-3 text-white"><Sparkles className="absolute right-3 top-3 text-lime-300" size={20}/><div className="mb-auto mt-8 text-center text-[10px] font-bold uppercase tracking-[.18em] text-slate-800">Le moment à retenir</div><p className="rounded-lg bg-black/45 p-2 text-center text-[11px] font-bold leading-snug">« Le meilleur contenu est celui que vous osez enfin partager. »</p><div className="mt-3 flex gap-1"><span className="h-1 flex-1 rounded-full bg-red-500"/><span className="h-1 flex-1 rounded-full bg-sky-500"/><span className="h-1 flex-1 rounded-full bg-pink-500"/></div></div></div>
    </div>
    <div className="absolute right-2 top-7 w-40 rounded-2xl border bg-white p-3 shadow-xl sm:right-4"><div className="mb-2 flex items-center justify-between"><p className="text-[10px] font-bold uppercase text-slate-400">6 clips prêts</p><Sparkles size={13} className="text-lime-600"/></div><div className="grid grid-cols-3 gap-1">{["object-left","object-center","object-right"].map((position,index)=><div key={position} className="relative aspect-[9/12] overflow-hidden rounded-md bg-slate-200"><Image src="/images/shortpilot-creator-story.png" alt="" fill className={`object-cover ${position}`}/><span className="absolute bottom-1 right-1 rounded bg-black/60 px-1 text-[7px] text-white">0:{18+index*7}</span></div>)}</div></div>
    <div className="absolute bottom-4 left-0 rounded-2xl bg-orange-500 px-4 py-3 text-white shadow-xl"><p className="flex items-center gap-2 text-sm font-bold"><Send size={16}/> 4 réseaux, un seul élan</p></div>
  </div>;
}

export default function LandingPage() {
  return <main className="overflow-hidden bg-[#fbfaf6] text-[#172033]">
    <nav className="fixed inset-x-0 top-0 z-50 border-b border-slate-900/5 bg-[#fbfaf6]/85 backdrop-blur-xl"><div className="mx-auto flex h-16 max-w-7xl items-center justify-between px-5"><Logo/><div className="hidden items-center gap-7 text-sm font-semibold md:flex"><a href="#histoire">Pourquoi</a><a href="#comment">Comment ça marche</a><a href="#tarifs">Tarifs</a></div><div className="flex items-center gap-3"><Link href="/login" className="hidden text-sm font-semibold sm:block">Se connecter</Link><Link href="/login" className="rounded-full bg-[#172033] px-5 py-2.5 text-sm font-bold text-white transition hover:-translate-y-0.5">Créer gratuitement</Link></div></div></nav>

    <section className="relative pt-32 sm:pt-40"><div className="absolute -left-32 top-24 h-72 w-72 rounded-full bg-lime-300/35 blur-3xl"/><div className="absolute -right-24 top-64 h-80 w-80 rounded-full bg-orange-300/35 blur-3xl"/><div className="relative mx-auto grid max-w-7xl items-center gap-8 px-5 pb-24 lg:grid-cols-[1.08fr_.92fr] lg:pb-32">
      <div><p className="mb-6 inline-flex items-center gap-2 rounded-full border bg-white px-4 py-2 text-xs font-bold uppercase tracking-[.12em] shadow-sm"><Sparkles size={14} className="text-orange-500"/> Créez une fois. Soyez visible partout.</p><h1 className="max-w-3xl text-[clamp(3.3rem,8vw,7.2rem)] font-black leading-[.86] tracking-[-.075em]">Une idée peut<br/><span className="relative text-orange-500">travailler plus.<svg className="absolute -bottom-3 left-0 w-full text-lime-500" viewBox="0 0 400 18" fill="none"><path d="M3 13C103 2 279 2 397 10" stroke="currentColor" strokeWidth="7" strokeLinecap="round"/></svg></span><br/>Pas vous.</h1><p className="mt-10 max-w-xl text-lg leading-8 text-slate-600 sm:text-xl">Transformez vos vidéos en contenus réguliers qui développent votre audience, attirent des clients et ouvrent la voie à vos revenus.</p><div className="mt-8 flex flex-wrap items-center gap-4"><Link href="/login" className="group inline-flex items-center gap-3 rounded-full bg-lime-500 px-7 py-4 font-black text-slate-950 shadow-lg shadow-lime-500/25 transition hover:-translate-y-1">Créer mes premiers Shorts <ArrowRight className="transition group-hover:translate-x-1" size={19}/></Link><a href="#pour-vous" className="inline-flex items-center gap-2 px-3 py-3 font-bold"><Play size={18}/> Trouver mon parcours</a></div><p className="mt-4 text-sm text-slate-500">3 créations offertes · Sans carte bancaire · Aucune promesse magique, un vrai rythme</p></div><ProductStory/>
    </div></section>

    <section id="histoire" className="bg-[#172033] py-24 text-white sm:py-32"><div className="mx-auto max-w-7xl px-5"><div className="grid items-center gap-12 lg:grid-cols-[.9fr_1.1fr]"><div className="relative aspect-[4/3] overflow-hidden rounded-[36px]"><Image src="/images/shortpilot-creator-story.png" alt="Une entrepreneure transforme son tournage en contenus courts" fill className="object-cover"/><div className="absolute inset-0 bg-gradient-to-t from-slate-950/60 to-transparent"/><p className="absolute bottom-5 left-5 right-5 text-sm font-bold uppercase tracking-[.16em] text-lime-300">Une caméra. Plusieurs semaines de contenu.</p></div><div><p className="text-sm font-bold uppercase tracking-[.2em] text-lime-400">Le vrai problème n’est pas le manque d’idées</p><h2 className="mt-5 text-4xl font-black leading-tight tracking-[-.045em] sm:text-6xl">C’est tout ce qui arrive <span className="text-orange-400">après « Coupez ! »</span></h2><p className="mt-6 max-w-xl text-lg leading-8 text-slate-300">Trouver le passage. Recadrer. Sous-titrer. Publier partout. ShortPilot transforme cette longue liste en un parcours simple.</p></div></div><div className="mt-16 grid gap-px overflow-hidden rounded-3xl bg-white/10 md:grid-cols-3"><article className="bg-[#172033] p-8"><Clock3 className="text-orange-400"/><h3 className="mt-8 text-2xl font-bold">Gagnez du temps</h3><p className="mt-3 text-slate-400">Concentrez-vous sur l’idée, pas sur quatre exports.</p></article><article className="bg-[#172033] p-8"><Layers3 className="text-lime-400"/><h3 className="mt-8 text-2xl font-bold">Publiez régulièrement</h3><p className="mt-3 text-slate-400">Un tournage devient une réserve de contenus.</p></article><article className="bg-[#172033] p-8"><Heart className="text-pink-400"/><h3 className="mt-8 text-2xl font-bold">Construisez quelque chose</h3><p className="mt-3 text-slate-400">Audience, clients ou revenus : vous choisissez le cap.</p></article></div></div></section>

    <section id="pour-vous" className="py-24 sm:py-32"><div className="mx-auto max-w-7xl px-5"><div className="grid gap-10 lg:grid-cols-[.75fr_1.25fr]"><div><p className="text-sm font-bold uppercase tracking-[.2em] text-orange-500">Un outil, plusieurs ambitions</p><h2 className="mt-4 text-4xl font-black tracking-[-.05em] sm:text-6xl">Quel est votre prochain cap ?</h2><p className="mt-6 text-lg leading-8 text-slate-600">ShortPilot s’adapte à ce que vous voulez construire — sans confondre régularité et succès garanti.</p></div><div className="grid gap-4 sm:grid-cols-2">
      {[{icon:Coins,title:"Monétiser une audience",text:"Publier avec constance et multiplier les occasions d’être découvert."},{icon:BriefcaseBusiness,title:"Trouver des clients",text:"Transformer votre expertise en contenus qui travaillent pour votre activité."},{icon:GraduationCap,title:"Recycler mes vidéos",text:"Faire vivre podcasts, formations et interviews après le tournage."},{icon:UsersRound,title:"Gérer plusieurs marques",text:"Organiser les comptes et publications de vos clients au même endroit."}].map(({icon:Icon,title,text})=><article key={title} className="rounded-[28px] border bg-white p-6 shadow-sm"><div className="grid h-12 w-12 place-items-center rounded-2xl bg-lime-100 text-lime-700"><Icon size={23}/></div><h3 className="mt-5 text-xl font-black">{title}</h3><p className="mt-2 leading-6 text-slate-600">{text}</p></article>)}
    </div></div></div></section>

    <section id="comment" className="bg-white py-24 sm:py-32"><div className="mx-auto max-w-7xl px-5"><div className="mx-auto max-w-3xl text-center"><p className="text-sm font-bold uppercase tracking-[.2em] text-orange-500">La magie, sans le mystère</p><h2 className="mt-4 text-4xl font-black tracking-[-.05em] sm:text-6xl">Un geste de votre côté.<br/>Tout un équipage du nôtre.</h2></div><div className="mt-20 grid gap-6 md:grid-cols-3">
      {[['01','Confiez votre source','Déposez une vidéo, collez un lien ou envoyez-la depuis Telegram. Votre histoire entre en piste.'],['02','Choisissez ce qui vous ressemble','ShortPilot propose les moments, le rythme, la voix et le format. Vous validez ce qui porte votre identité.'],['03','Laissez-la voyager','YouTube, TikTok, Instagram et Facebook reçoivent chacun une publication adaptée, au moment choisi.']].map(([n,title,text])=><article key={n} className="group rounded-[32px] border bg-white p-8 transition hover:-translate-y-2 hover:shadow-2xl hover:shadow-slate-900/10"><span className="text-6xl font-black text-slate-100 transition group-hover:text-lime-200">{n}</span><h3 className="mt-8 text-2xl font-black">{title}</h3><p className="mt-4 leading-7 text-slate-600">{text}</p><ChevronRight className="mt-8 text-orange-500"/></article>)}
    </div></div></section>

    <section className="px-5 py-12 sm:py-20"><div className="mx-auto max-w-7xl overflow-hidden rounded-[42px] bg-orange-500 px-6 py-14 text-white sm:px-14 lg:px-20"><div className="grid items-center gap-12 lg:grid-cols-2"><div><WandSparkles size={34}/><h2 className="mt-7 text-4xl font-black tracking-[-.05em] sm:text-6xl">Ce n’est pas publier plus.<br/>C’est être plus présent.</h2><p className="mt-6 max-w-xl text-lg leading-8 text-orange-50">Une même idée peut rencontrer quelqu’un dans un Short au réveil, un Reel à midi ou un carrousel le soir. ShortPilot ne remplace pas votre voix. Il lui ouvre plusieurs portes.</p></div><div className="grid grid-cols-2 gap-4">{['YouTube','TikTok','Instagram','Facebook'].map((network,i)=><div key={network} className={`rounded-3xl border border-white/20 bg-white/10 p-6 backdrop-blur ${i%2?'translate-y-5':''}`}><div className="mb-10 h-3 w-3 rounded-full bg-lime-300"/><p className="text-xl font-black">{network}</p><p className="mt-1 text-sm text-orange-100">Une version pensée pour sa destination.</p></div>)}</div></div></div></section>

    <section id="tarifs" className="py-24 sm:py-32"><div className="mx-auto max-w-7xl px-5"><div className="max-w-3xl"><p className="text-sm font-bold uppercase tracking-[.2em] text-lime-700">Des prix qui laissent respirer</p><h2 className="mt-4 text-4xl font-black tracking-[-.05em] sm:text-6xl">Commencez avec une idée.<br/>Grandissez avec vos histoires.</h2></div><div className="mt-16 grid items-stretch gap-6 lg:grid-cols-3">{plans.map(plan=><article key={plan.name} className={`relative flex flex-col rounded-[30px] border p-8 ${plan.featured?'border-[#172033] bg-[#172033] text-white shadow-2xl lg:-translate-y-4':'bg-white'}`}>{plan.featured&&<span className="absolute right-6 top-6 rounded-full bg-lime-400 px-3 py-1 text-xs font-black text-slate-900">LE PLUS CHOISI</span>}<h3 className="text-2xl font-black">{plan.name}</h3><p className={`mt-4 min-h-20 ${plan.featured?'text-slate-300':'text-slate-600'}`}>{plan.description}</p><div className="my-7 flex items-end gap-2"><span className="text-6xl font-black tracking-[-.06em]">{plan.price}</span><span className={`pb-2 text-sm ${plan.featured?'text-slate-400':'text-slate-500'}`}>{plan.suffix}</span></div><ul className="mb-8 space-y-3">{plan.features.map(feature=><li key={feature} className="flex gap-3 text-sm"><Check size={18} className="shrink-0 text-lime-500"/>{feature}</li>)}</ul><Link href="/login" className={`mt-auto rounded-full px-5 py-3 text-center text-sm font-black ${plan.featured?'bg-lime-400 text-slate-950':'bg-slate-100'}`}>{plan.cta}</Link></article>)}</div><p className="mt-6 text-center text-sm text-slate-500">Une création correspond à un rendu court réussi. Publier ce rendu sur plusieurs réseaux ne consomme pas de crédit supplémentaire.</p></div></section>

    <section className="border-y bg-white py-24"><div className="mx-auto max-w-4xl px-5"><p className="text-center text-sm font-bold uppercase tracking-[.2em] text-orange-500">Questions honnêtes, réponses simples</p><div className="mt-12 divide-y">{faqs.map(([q,a])=><details key={q} className="group py-6"><summary className="flex cursor-pointer list-none items-center justify-between gap-6 text-xl font-black">{q}<span className="grid h-8 w-8 shrink-0 place-items-center rounded-full bg-slate-100 text-xl transition group-open:rotate-45">+</span></summary><p className="max-w-2xl pt-4 leading-7 text-slate-600">{a}</p></details>)}</div></div></section>

    <section className="relative overflow-hidden bg-lime-400 py-24 text-center sm:py-32"><div className="absolute inset-0 opacity-20 [background-image:radial-gradient(#172033_1px,transparent_1px)] [background-size:18px_18px]"/><div className="relative mx-auto max-w-4xl px-5"><p className="text-sm font-bold uppercase tracking-[.2em]">Votre prochaine publication est peut-être déjà tournée</p><h2 className="mt-5 text-5xl font-black leading-[.95] tracking-[-.06em] sm:text-7xl">Rouvrez ce dossier.<br/>On s’occupe de la suite.</h2><Link href="/login" className="mt-9 inline-flex items-center gap-3 rounded-full bg-[#172033] px-8 py-4 font-black text-white">Créer mes premiers contenus <ArrowRight size={19}/></Link></div></section>

    <footer className="bg-[#172033] py-12 text-white"><div className="mx-auto grid max-w-7xl gap-9 px-5 md:grid-cols-[1fr_1.3fr_auto]"><div><Logo inverted/><p className="mt-4 max-w-xs text-sm leading-6 text-slate-400">Une idée, plusieurs formats, une audience sans frontières.</p></div><div className="grid grid-cols-2 gap-5 text-sm text-slate-300 sm:grid-cols-3"><div><p className="mb-3 font-bold text-white">Produit</p><a href="#comment" className="block py-1">Fonctionnement</a><a href="#tarifs" className="block py-1">Tarifs</a></div><div><p className="mb-3 font-bold text-white">Communauté</p><Link href="/partners" className="block py-1 text-lime-400">Devenir partenaire</Link><Link href="/login" className="block py-1">Connexion</Link></div><div><p className="mb-3 font-bold text-white">Langue</p><label className="flex w-fit items-center gap-2 rounded-full border border-white/15 px-3 py-2"><Languages size={15}/><select aria-label="Choisir la langue" defaultValue="fr" className="bg-transparent text-sm outline-none"><option value="fr" className="text-slate-900">Français</option><option value="en" className="text-slate-900">English — bientôt</option></select></label></div></div><p className="text-xs text-slate-500 md:text-right">© 2026 ShortPilot<br/>Pensé pour créer partout.</p></div></footer>
  </main>;
}
