"use client";
import Image from "next/image";
import Link from "next/link";
import { useState } from "react";
import { ArrowLeft, ArrowRight, Captions, Check, Clock3, Crop, Play, RotateCcw, Sparkles, WandSparkles } from "lucide-react";

const clips=[{id:1,title:"Le déclic que personne ne voit",score:94,time:"02:14 – 02:47",duration:"0:33",position:"object-left"},{id:2,title:"L’erreur qui coûte le plus de temps",score:89,time:"11:06 – 11:34",duration:"0:28",position:"object-center"},{id:3,title:"La méthode en trois étapes",score:86,time:"23:41 – 24:18",duration:"0:37",position:"object-right"},{id:4,title:"Ce que je ferais différemment",score:82,time:"39:10 – 39:42",duration:"0:32",position:"object-left"}];

export function Studio(){
 const [active,setActive]=useState(1);const [selected,setSelected]=useState<number[]>([1,2,3]);const [format,setFormat]=useState("9:16");const [captions,setCaptions]=useState("Dynamique");const current=clips.find(clip=>clip.id===active)??clips[0];const toggle=(id:number)=>setSelected(items=>items.includes(id)?items.filter(item=>item!==id):[...items,id]);
 return <div className="mx-auto max-w-[1500px]"><header className="flex flex-wrap items-end justify-between gap-4"><div><Link href="/dashboard/videos" className="mb-4 flex items-center gap-2 text-sm font-bold text-slate-500"><ArrowLeft size={16}/> Bibliothèque</Link><p className="text-sm font-black uppercase tracking-[.15em] text-lime-700">Studio de transformation</p><h1 className="mt-1 text-3xl font-black tracking-[-.04em] md:text-4xl">Podcast — Épisode 12</h1><p className="mt-2 text-sm text-slate-500">6 moments détectés · 47:12 de source</p></div><Link href="/dashboard/publications/new" className={`flex items-center gap-2 rounded-full px-5 py-3 text-sm font-black ${selected.length?"bg-[#172033] text-white":"pointer-events-none bg-slate-200 text-slate-400"}`}>Préparer {selected.length} publication{selected.length>1?"s":""}<ArrowRight size={17}/></Link></header>
 <div className="mt-7 grid gap-5 xl:grid-cols-[310px_minmax(300px,1fr)_300px]"><section className="order-2 overflow-hidden rounded-3xl border bg-white xl:order-1"><div className="border-b p-5"><h2 className="font-black">Moments proposés</h2><p className="text-xs text-slate-500">Gardez uniquement les meilleurs.</p></div><div className="max-h-[680px] divide-y overflow-y-auto">{clips.map(clip=><button key={clip.id} onClick={()=>setActive(clip.id)} className={`flex w-full gap-3 p-3 text-left transition ${active===clip.id?"bg-lime-50":"hover:bg-slate-50"}`}><span onClick={event=>{event.stopPropagation();toggle(clip.id)}} className={`mt-1 grid h-5 w-5 shrink-0 place-items-center rounded border ${selected.includes(clip.id)?"border-lime-600 bg-lime-600 text-white":"bg-white"}`}>{selected.includes(clip.id)&&<Check size={13}/>}</span><span className="relative h-16 w-12 shrink-0 overflow-hidden rounded-lg"><Image src="/images/omnelyo-creator-story.png" alt="" fill className={`object-cover ${clip.position}`}/></span><span className="min-w-0 flex-1"><span className="line-clamp-2 text-sm font-bold">{clip.title}</span><span className="mt-2 flex items-center justify-between text-[11px] text-slate-500"><span>{clip.time}</span><span className="font-black text-lime-700">{clip.score}/100</span></span></span></button>)}</div></section>
 <section className="order-1 rounded-3xl bg-[#172033] p-4 xl:order-2"><div className="mx-auto max-w-[290px]"><div className={`relative overflow-hidden rounded-[28px] bg-slate-900 ${format==="9:16"?"aspect-[9/16]":format==="1:1"?"aspect-square":"aspect-[4/5]"}`}><Image src="/images/omnelyo-creator-story.png" alt={`Aperçu de ${current.title}`} fill className={`object-cover ${current.position}`}/><div className="absolute inset-0 bg-gradient-to-t from-black/60 via-transparent to-black/10"/><button aria-label="Lire l’extrait" className="absolute inset-0 m-auto grid h-12 w-12 place-items-center rounded-full bg-white/90"><Play size={17} fill="currentColor"/></button><div className="absolute inset-x-4 bottom-8 rounded-xl bg-black/55 p-2 text-center text-sm font-black text-white backdrop-blur">Le meilleur moment arrive quand on arrête de le forcer.</div><span className="absolute left-3 top-3 rounded-full bg-lime-400 px-2 py-1 text-[10px] font-black">Score {current.score}</span></div><div className="mt-4 flex items-center justify-between text-white"><div><p className="text-sm font-black">{current.title}</p><p className="mt-1 flex items-center gap-1 text-xs text-slate-400"><Clock3 size={12}/>{current.time} · {current.duration}</p></div><button aria-label="Rejouer"><RotateCcw size={18}/></button></div></div></section>
 <aside className="order-3 space-y-4"><section className="rounded-3xl border bg-white p-5"><div className="flex items-center gap-2"><Crop size={18} className="text-orange-500"/><h2 className="font-black">Format</h2></div><div className="mt-4 grid grid-cols-3 gap-2">{["9:16","4:5","1:1"].map(value=><button key={value} onClick={()=>setFormat(value)} className={`rounded-xl border px-2 py-3 text-xs font-black ${format===value?"border-slate-900 bg-slate-900 text-white":"bg-slate-50"}`}>{value}</button>)}</div></section><section className="rounded-3xl border bg-white p-5"><div className="flex items-center gap-2"><Captions size={18} className="text-lime-600"/><h2 className="font-black">Sous-titres</h2></div><div className="mt-4 space-y-2">{["Dynamique","Minimal","Sans sous-titres"].map(value=><button key={value} onClick={()=>setCaptions(value)} className={`flex w-full items-center justify-between rounded-xl border px-3 py-2.5 text-sm font-bold ${captions===value?"border-lime-500 bg-lime-50":""}`}>{value}{captions===value&&<Check size={15}/>}</button>)}</div></section><section className="rounded-3xl bg-orange-50 p-5"><WandSparkles className="text-orange-600"/><h2 className="mt-3 font-black">Pourquoi cet extrait ?</h2><p className="mt-2 text-sm leading-6 text-slate-600">Accroche claire, idée autonome et changement de rythme favorable à la rétention.</p><p className="mt-3 flex items-center gap-1 text-xs font-bold text-orange-700"><Sparkles size={13}/> Suggestion IA à valider</p></section></aside></div><p className="mt-5 text-xs text-slate-400">Interface de démonstration — les découpes et scores seront fournis par les jobs de traitement.</p></div>;
}
